# Generated by Django 2.1.4 on 2019-02-07 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderclient', models.CharField(max_length=255)),
                ('orderplacedate', models.DateField()),
                ('orderdeliverydate', models.DateField()),
                ('orderaddress', models.CharField(max_length=255)),
                ('orderinstructions', models.TextField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productdescription', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.TextField()),
                ('typeuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'producttypes',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewcomment', models.TextField()),
                ('reviewrating', models.SmallIntegerField()),
                ('reviewdate', models.DateField()),
                ('reviewreply', models.TextField()),
                ('revieworder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.Orders')),
                ('reviewproduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.Products')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='producttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.ProductTypes'),
        ),
        migrations.AddField(
            model_name='products',
            name='productuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='orderproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storeapp.Products'),
        ),
    ]
