# Generated by Django 2.1.4 on 2019-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_auto_20190207_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewreply',
            field=models.TextField(blank=True),
        ),
    ]
